# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:
  - Name: Orderers
    Domain: orderersorg
    Template:
      Count: 3

PeerOrgs:
  - Name: OrderOrg
    Domain: orderorg
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: ContractorOrg
    Domain: contractororg
    Template:
      Count: 2
      Start: 2
    Users:
      Count: 1

  - Name: SubContractorOrg
    Domain: subcontractororg
    Template:
      Count: 2
      Start: 4
    Users:
      Count: 1

  - Name: DataProviderOrg
    Domain: dataproviderorg
    Template:
      Count: 1
      Start: 6
    Users:
      Count: 1

  - Name: GovernanceOrg
    Domain: governanceorg
    Template:
      Count: 3
      Start: 7
    Users:
      Count: 1